[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10

[env]
TERM="xterm-256color"
